-- ----------------------------
-- Table structure for SYS_RESOURCE_ITEM_ASSIGN
-- ----------------------------
CREATE TABLE "SYS_RESOURCE_ITEM_ASSIGN" (
  "ASSIGN_ID" NUMBER(38) NOT NULL ,
  "ASSIGN_TYPE" VARCHAR2(50) ,
  "TYPE_ID" NUMBER(38) ,
  "ELEMENT_ID" NUMBER(38) ,
  "FUNCTION_ID" NUMBER(38) ,
  "ENABLE" VARCHAR2(50) ,
  "OBJECT_VERSION_NUMBER" NUMBER(38) DEFAULT 1 ,
  "REQUEST_ID" NUMBER(38) DEFAULT -1 ,
  "PROGRAM_ID" NUMBER(38) DEFAULT -1 ,
  "CREATED_BY" NUMBER(38) DEFAULT -1 ,
  "CREATION_DATE" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP ,
  "LAST_UPDATED_BY" NUMBER(38) DEFAULT -1 ,
  "LAST_UPDATE_DATE" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP ,
  "LAST_UPDATE_LOGIN" NUMBER(38) DEFAULT -1 ,
  "ATTRIBUTE_CATEGORY" VARCHAR2(30) ,
  "ATTRIBUTE1" VARCHAR2(240) ,
  "ATTRIBUTE2" VARCHAR2(240) ,
  "ATTRIBUTE3" VARCHAR2(240) ,
  "ATTRIBUTE4" VARCHAR2(240) ,
  "ATTRIBUTE5" VARCHAR2(240) ,
  "ATTRIBUTE6" VARCHAR2(240) ,
  "ATTRIBUTE7" VARCHAR2(240) ,
  "ATTRIBUTE8" VARCHAR2(240) ,
  "ATTRIBUTE9" VARCHAR2(240) ,
  "ATTRIBUTE10" VARCHAR2(240) ,
  "ATTRIBUTE11" VARCHAR2(240) ,
  "ATTRIBUTE12" VARCHAR2(240) ,
  "ATTRIBUTE13" VARCHAR2(240) ,
  "ATTRIBUTE14" VARCHAR2(240) ,
  "ATTRIBUTE15" VARCHAR2(240) 
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SYS_RESOURCE_ITEM_ASSIGN"."ASSIGN_ID" IS 'PK';
COMMENT ON COLUMN "SYS_RESOURCE_ITEM_ASSIGN"."ASSIGN_TYPE" IS '分配类型';
COMMENT ON COLUMN "SYS_RESOURCE_ITEM_ASSIGN"."TYPE_ID" IS '类型ID';
COMMENT ON COLUMN "SYS_RESOURCE_ITEM_ASSIGN"."ELEMENT_ID" IS '组件元素ID';
COMMENT ON COLUMN "SYS_RESOURCE_ITEM_ASSIGN"."FUNCTION_ID" IS '功能ID';
COMMENT ON COLUMN "SYS_RESOURCE_ITEM_ASSIGN"."ENABLE" IS '是否启用';
COMMENT ON TABLE "SYS_RESOURCE_ITEM_ASSIGN" IS '资源组件分配';

-- ----------------------------
-- Primary Key structure for table SYS_RESOURCE_ITEM_ASSIGN
-- ----------------------------
ALTER TABLE "SYS_RESOURCE_ITEM_ASSIGN" ADD CONSTRAINT "SYS_RESOURCE_ITEM_ASSIGN_PK" PRIMARY KEY ("ASSIGN_ID");


CREATE SEQUENCE  "SYS_RESOURCE_ITEM_ASSIGN_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10001 CACHE 20 NOORDER  NOCYCLE
