-- ----------------------------
-- Table structure for SYS_RESOURCE_ITEM_ELEMENT
-- ----------------------------
CREATE TABLE "SYS_RESOURCE_ITEM_ELEMENT" (
  "ELEMENT_ID" NUMBER(38) NOT NULL ,
  "TYPE" VARCHAR2(20 BYTE) NOT NULL ,
  "PROPERTY" VARCHAR2(20 BYTE) NOT NULL ,
  "PROPERTY_VALUE" VARCHAR2(20 BYTE) NOT NULL ,
  "NAME" VARCHAR2(20 BYTE) ,
  "RESOURCE_ITEM_ID" NUMBER(38) ,
  "OBJECT_VERSION_NUMBER" NUMBER(38) DEFAULT 1 ,
  "REQUEST_ID" NUMBER(38) DEFAULT -1 ,
  "PROGRAM_ID" NUMBER(38) DEFAULT -1 ,
  "CREATED_BY" NUMBER(38) DEFAULT -1 ,
  "CREATION_DATE" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP ,
  "LAST_UPDATED_BY" NUMBER(38) DEFAULT -1 ,
  "LAST_UPDATE_DATE" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP ,
  "LAST_UPDATE_LOGIN" NUMBER(38) DEFAULT -1 ,
  "ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE) ,
  "ATTRIBUTE1" VARCHAR2(240 BYTE) ,
  "ATTRIBUTE2" VARCHAR2(240 BYTE) ,
  "ATTRIBUTE3" VARCHAR2(240 BYTE) ,
  "ATTRIBUTE4" VARCHAR2(240 BYTE) ,
  "ATTRIBUTE5" VARCHAR2(240 BYTE) ,
  "ATTRIBUTE6" VARCHAR2(240 BYTE) ,
  "ATTRIBUTE7" VARCHAR2(240 BYTE) ,
  "ATTRIBUTE8" VARCHAR2(240 BYTE) ,
  "ATTRIBUTE9" VARCHAR2(240 BYTE) ,
  "ATTRIBUTE10" VARCHAR2(240 BYTE) ,
  "ATTRIBUTE11" VARCHAR2(240 BYTE) ,
  "ATTRIBUTE12" VARCHAR2(240 BYTE) ,
  "ATTRIBUTE13" VARCHAR2(240 BYTE) ,
  "ATTRIBUTE14" VARCHAR2(240 BYTE) ,
  "ATTRIBUTE15" VARCHAR2(240 BYTE) 
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SYS_RESOURCE_ITEM_ELEMENT"."ELEMENT_ID" IS 'PK';
COMMENT ON COLUMN "SYS_RESOURCE_ITEM_ELEMENT"."TYPE" IS '类型';
COMMENT ON COLUMN "SYS_RESOURCE_ITEM_ELEMENT"."PROPERTY" IS '属性';
COMMENT ON COLUMN "SYS_RESOURCE_ITEM_ELEMENT"."PROPERTY_VALUE" IS '属性值';
COMMENT ON COLUMN "SYS_RESOURCE_ITEM_ELEMENT"."NAME" IS '名称';
COMMENT ON COLUMN "SYS_RESOURCE_ITEM_ELEMENT"."RESOURCE_ITEM_ID" IS '资源组件ID';
COMMENT ON TABLE "SYS_RESOURCE_ITEM_ELEMENT" IS '资源组件元素';

-- ----------------------------
-- Primary Key structure for table SYS_RESOURCE_ITEM_ELEMENT
-- ----------------------------
ALTER TABLE "SYS_RESOURCE_ITEM_ELEMENT" ADD CONSTRAINT "SYS_RESOURCE_ITEM_ELEMENT_PK" PRIMARY KEY ("ELEMENT_ID");

CREATE SEQUENCE  "SYS_RESOURCE_ITEM_ELEMENT_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10001 CACHE 20 NOORDER  NOCYCLE
