
CREATE TABLE "SYS_USER_HOME_PAGE" (
  "USER_HOME_PAGE_ID" NUMBER NOT NULL ,
  "ROLE_ID" NUMBER ,
  "USER_ID" NUMBER ,
  "CONTENT" CLOB ,
  "OBJECT_VERSION_NUMBER" NUMBER DEFAULT 1 ,
  "REQUEST_ID" NUMBER ,
  "PROGRAM_ID" NUMBER ,
  "CREATED_BY" NUMBER ,
  "CREATION_DATE" DATE DEFAULT sysdate ,
  "LAST_UPDATED_BY" NUMBER ,
  "LAST_UPDATE_DATE" DATE DEFAULT sysdate ,
  "LAST_UPDATE_LOGIN" NUMBER ,
  "FUNCTION_CODE" VARCHAR2(200 BYTE) DEFAULT '功能代码'  NOT NULL ,
  "THEME" VARCHAR2(255 BYTE) ,
  "SUBJECT" VARCHAR2(255 BYTE) 
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Primary Key structure for table SYS_USER_HOME_PAGE
-- ----------------------------
ALTER TABLE "SYS_USER_HOME_PAGE" ADD CONSTRAINT "SYS_C00143310" PRIMARY KEY ("USER_HOME_PAGE_ID");



CREATE SEQUENCE  "SYS_USER_HOME_PAGE_S"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;


