
-- ----------------------------
-- Table structure for SYS_ROLE_WIDGET
-- ----------------------------
CREATE TABLE "SYS_ROLE_WIDGET" (
  "WIDGET_ID" NUMBER NOT NULL ,
  "ROLE_ID" NUMBER ,
  "FUNCTION_CODE" VARCHAR2(200 BYTE) ,
  "OBJECT_VERSION_NUMBER" NUMBER DEFAULT 1 ,
  "REQUEST_ID" NUMBER ,
  "PROGRAM_ID" NUMBER ,
  "CREATED_BY" NUMBER ,
  "CREATION_DATE" DATE DEFAULT sysdate ,
  "LAST_UPDATED_BY" NUMBER ,
  "LAST_UPDATE_DATE" DATE DEFAULT sysdate ,
  "LAST_UPDATE_LOGIN" NUMBER ,
  "ENABLED_FLAG" VARCHAR2(1 BYTE) ,
  "IMAGE" VARCHAR2(200 BYTE) ,
  "SUBJECT" VARCHAR2(255 BYTE) 
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SYS_ROLE_WIDGET"."ENABLED_FLAG" IS '启用';

-- Primary Key structure for table SYS_ROLE_WIDGET
-- ----------------------------
ALTER TABLE "SYS_ROLE_WIDGET" ADD CONSTRAINT "SYS_C00142499" PRIMARY KEY ("WIDGET_ID");

