ALTER TABLE "EXP_EMPLOYEES"
 ADD ("DATA_ID" NUMBER(20) DEFAULT '1' );

ALTER TABLE "EXP_EMPLOYEES"
 ADD ("BORN_DATE" TIMESTAMP(6) );

ALTER TABLE "EXP_EMPLOYEES"
 ADD ("JOIN_DATE" TIMESTAMP(6) );

ALTER TABLE "EXP_EMPLOYEES"
 ADD ("GENDER" VARCHAR2(1) DEFAULT null );

ALTER TABLE "EXP_EMPLOYEES"
 ADD ("CERTIFICATE_ID" VARCHAR2(100) );

ALTER TABLE "EXP_EMPLOYEES"
 ADD ("STATUS" VARCHAR2(50));

ALTER TABLE "EXP_EMPLOYEES" 
ADD ( "REQUEST_ID" NUMBER ( 20 ) DEFAULT '-1' );

ALTER TABLE "EXP_EMPLOYEES" 
ADD ("PROGRAM_ID" NUMBER(20) DEFAULT '-1' );

ALTER TABLE "EXP_EMPLOYEES" 
ADD ("LAST_UPDATE_LOGIN" NUMBER(20) DEFAULT '-1' );

ALTER TABLE "EXP_EMPLOYEES" 
ADD ("ATTRIBUTE_CATEGORY" VARCHAR2(30) );

ALTER TABLE "EXP_EMPLOYEES" 
ADD ("ATTRIBUTE1" VARCHAR2(240) );

ALTER TABLE "EXP_EMPLOYEES" 
ADD ("ATTRIBUTE2" VARCHAR2(240) );

ALTER TABLE "EXP_EMPLOYEES" 
ADD ("ATTRIBUTE3" VARCHAR2(240) );

ALTER TABLE "EXP_EMPLOYEES" 
ADD ("ATTRIBUTE4" VARCHAR2(240) );

ALTER TABLE "EXP_EMPLOYEES" 
ADD ("ATTRIBUTE5" VARCHAR2(240) );

ALTER TABLE "EXP_EMPLOYEES" 
ADD ("ATTRIBUTE6" VARCHAR2(240) );

ALTER TABLE "EXP_EMPLOYEES" 
ADD ("ATTRIBUTE7" VARCHAR2(240) );

ALTER TABLE "EXP_EMPLOYEES" 
ADD ("ATTRIBUTE8" VARCHAR2(240) );

ALTER TABLE "EXP_EMPLOYEES" 
ADD ("ATTRIBUTE9" VARCHAR2(240) );

ALTER TABLE "EXP_EMPLOYEES" 
ADD ("ATTRIBUTE10" VARCHAR2(240) );

ALTER TABLE "EXP_EMPLOYEES" 
ADD ("ATTRIBUTE11" VARCHAR2(240) );

ALTER TABLE "EXP_EMPLOYEES" 
ADD ("ATTRIBUTE12" VARCHAR2(240) );

ALTER TABLE "EXP_EMPLOYEES" 
ADD ("ATTRIBUTE13" VARCHAR2(240) );

ALTER TABLE "EXP_EMPLOYEES" 
ADD ("ATTRIBUTE14" VARCHAR2(240) );

ALTER TABLE "EXP_EMPLOYEES" 
ADD ("ATTRIBUTE15" VARCHAR2(240) );