ALTER TABLE "EXP_ORG_UNIT" 
ADD ( "PARENT_ID" NUMBER ( 20 ) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ( "NAME"  VARCHAR2(100) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ( "DESCRIPTION" VARCHAR2(255));

ALTER TABLE "EXP_ORG_UNIT" 
ADD ( "MANAGER_POSITION" NUMBER ( 20 ) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ( "UNIT_CATEGORY"  VARCHAR2(50) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ( "UNIT_TYPE" VARCHAR2(50) DEFAULT 'GROUP' );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ( "REQUEST_ID" NUMBER ( 20 ) DEFAULT '-1' );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ("PROGRAM_ID" NUMBER(20) DEFAULT '-1' );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ("LAST_UPDATE_LOGIN" NUMBER(20) DEFAULT '-1' );

ALTER TABLE "EXP_ORG_UNIT"
ADD ("DATA_ID" NUMBER(20) );


ALTER TABLE "EXP_ORG_UNIT" 
ADD ("ATTRIBUTE_CATEGORY" VARCHAR2(30) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ("ATTRIBUTE1" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ("ATTRIBUTE2" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ("ATTRIBUTE3" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ("ATTRIBUTE4" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ("ATTRIBUTE5" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ("ATTRIBUTE6" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ("ATTRIBUTE7" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ("ATTRIBUTE8" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ("ATTRIBUTE9" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ("ATTRIBUTE10" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ("ATTRIBUTE11" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ("ATTRIBUTE12" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ("ATTRIBUTE13" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ("ATTRIBUTE14" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_UNIT" 
ADD ("ATTRIBUTE15" VARCHAR2(240) );