-- ----------------------------
-- Table structure for EXP_ORG_POSITION
-- ----------------------------

ALTER TABLE "EXP_ORG_POSITION"
 ADD ("NAME" VARCHAR2(30) );

ALTER TABLE "EXP_ORG_POSITION"
 ADD ("DESCRIPTION" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_POSITION"
 ADD ("OBJECT_VERSION_NUMBER" NUMBER(20) DEFAULT '1' );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ( "REQUEST_ID" NUMBER ( 20 ) DEFAULT '-1' );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ("PROGRAM_ID" NUMBER(20) DEFAULT '-1' );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ("LAST_UPDATE_LOGIN" NUMBER(20) DEFAULT '-1' );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ("ATTRIBUTE_CATEGORY" VARCHAR2(30) );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ("ATTRIBUTE1" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ("ATTRIBUTE2" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ("ATTRIBUTE3" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ("ATTRIBUTE4" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ("ATTRIBUTE5" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ("ATTRIBUTE6" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ("ATTRIBUTE7" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ("ATTRIBUTE8" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ("ATTRIBUTE9" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ("ATTRIBUTE10" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ("ATTRIBUTE11" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ("ATTRIBUTE12" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ("ATTRIBUTE13" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ("ATTRIBUTE14" VARCHAR2(240) );

ALTER TABLE "EXP_ORG_POSITION" 
ADD ("ATTRIBUTE15" VARCHAR2(240) );