ALTER TABLE "EXP_EMPLOYEE_ASSIGNS"
 ADD ("OBJECT_VERSION_NUMBER" NUMBER(20) DEFAULT '1' );

ALTER TABLE "EXP_EMPLOYEE_ASSIGNS" 
ADD ( "REQUEST_ID" NUMBER ( 20 ) DEFAULT '-1' );

ALTER TABLE "EXP_EMPLOYEE_ASSIGNS" 
ADD ("PROGRAM_ID" NUMBER(20) DEFAULT '-1' );

ALTER TABLE "EXP_EMPLOYEE_ASSIGNS" 
ADD ("LAST_UPDATE_LOGIN" NUMBER(20) DEFAULT '-1' );