ALTER TABLE "PRJ_PROJECT" 
ADD ("PROJECT_TYPE" VARCHAR2(30 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("PROJECT_SCALE" VARCHAR2(30 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("OBJECT_DESCRIPTION" VARCHAR2(4000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("BUSINESS_DESCRIPTION" VARCHAR2(4000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("FUND_PURPOSE_DESCRIPTION" VARCHAR2(4000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_PROGRAMME_DESCRIPTION" VARCHAR2(4000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_IDENTIFICATION_BASIS" VARCHAR2(4000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("DATA_ID" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("PRJ_COMPLIANCE_DEGREE" VARCHAR2(4000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("PRJ_KEY_POINT" VARCHAR2(4000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("RISK_CONTROL_ESTIMATE" VARCHAR2(4000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("FAVORABLE_FACTOR" VARCHAR2(4000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("NEGATIVE_FACTOR" VARCHAR2(4000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_FORM" VARCHAR2(50 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("INVESTMENT_PLAN_PROGRESS" VARCHAR2(1000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("ACTUAL_FINANCING" VARCHAR2(1000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("REQUIREMENT_PURPOSE_ANALYSIS" VARCHAR2(1000 BYTE) );


ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_INSURANCE_TYPE" VARCHAR2(100 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_INSURANCE_PARTY" VARCHAR2(30 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_INSURANCE_TERM" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_INSURANCE_NOTE" VARCHAR2(2000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("CREDIT_OCCUPY_CREDIT_ID" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("CREDIT_ADV_OCCUPY_ID" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("FINANCIAL_STATUS" VARCHAR2(4000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("REPORT_FORMS_DISCREPANCY" VARCHAR2(4000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("FORMS_CHECK_STATUS" VARCHAR2(4000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_PLEDGE" VARCHAR2(10 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_INVOICE_WAY" VARCHAR2(400 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("DATA_CLASS" VARCHAR2(50 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("VIRTUAL_CON_NUMBER" VARCHAR2(50 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("CONTENT_FINISH_FLAG" VARCHAR2(1 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("COFIRM_QUOTATION_FLAG" VARCHAR2(1 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("PRE_RENTAL_BUSINESS" VARCHAR2(50 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("VIRTUAL_CON_NAME" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("CONTENT_INSTANCE_ID" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("CONTENT_WFL_STATUS" VARCHAR2(100 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("SIGNING_PERSON_ID" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("SIGNING_DATE" DATE );

ALTER TABLE "PRJ_PROJECT" 
ADD ("SIGNING_DESCRIPTION" VARCHAR2(2000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("SIGNING_PLACE" VARCHAR2(500 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("SCORE_FLAG" VARCHAR2(1 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("EBS_PROJECT_CODE" VARCHAR2(30 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("TRUST_MEASURE" VARCHAR2(1000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("PRJ_SCALE" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("PRJ_DATE" DATE );

ALTER TABLE "PRJ_PROJECT" 
ADD ("TOTAL_INVESTMENT" VARCHAR2(100 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_TOTAL_PRICE" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("CO_TYPE" VARCHAR2(100 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("CO_UNION" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("CHANCE_ADVICE" VARCHAR2(2000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("CHANCE_ADVICE_CARRY" VARCHAR2(2000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_B_NAME" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_B_USAGE" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_B_SUP" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_B_TECH" VARCHAR2(2000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_B_TYPE" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_B_CORE" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_B_CORE_PRICE" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_B_TPRICE" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_B_CPRICE" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_B_TIME" DATE );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_B_DEP" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_B_LYEAR" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_B_AYEAR" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_B_TYEAR" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_B_ALYEAR" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_B_SUPERVISE" VARCHAR2(2000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_B_GENERAL" VARCHAR2(2000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_ALR_NUMBER" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_ALR_TYPE" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_ALR_WAY" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_ALR_COMPANY" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_IN_START" DATE );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_IN_END" DATE );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_IN_AMOUNT" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_IN_COMPANY" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_IN_PAY" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_IN_NUMBER" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_IN_OTHER" VARCHAR2(2000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LEASE_ITEM_IN_CONFER" VARCHAR2(2000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("BINARY_CLASSIFICATION" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("CREDIT_REFEREE" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("HN_INDUSTRY_CLASSIFICATION" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("OTHER_TRANSACTION_CONDITION" VARCHAR2(1000 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("LAW_FIRM" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("ACCOUNTING_FIRM" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("TEST_CERTIFICATION_AUTHORITY" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("TECH_CONSULTING_AUTHORITY" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("PRJ_WFL_STATUS" VARCHAR2(30 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("APPROVAL_COUNT" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("DISCUSS_COUNT" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("REF_PROJECT_ID" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("GROUP_LEADER" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("SEAL_TYPE" VARCHAR2(400 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("SEAL_NUMBER" VARCHAR2(50 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("REGION_OF_CHINA" VARCHAR2(50 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("PROJECT_LOCATION" VARCHAR2(200 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("PROJECT_INTRODUCTION" CLOB );

ALTER TABLE "PRJ_PROJECT" 
ADD ("COUNTRY_ID" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("PROVINCE_ID" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("CITY_ID" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("DISTRICT_ID" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("HN_PRJ_INCREASING_TRUST" VARCHAR2(400 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("SERVICE_CON_NUMBER" VARCHAR2(30 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("RISK_ACTION_TYPE" VARCHAR2(30 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("WFL_INSTANCE_ID_2" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("WFL_INSTANCE_ID_3" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("PRJ_APPROVED_DATE" DATE );

ALTER TABLE "PRJ_PROJECT" 
ADD ("PRJ_LEASE_SCHEME" CLOB );

ALTER TABLE "PRJ_PROJECT" 
ADD ("RISK_REVEAL" CLOB );

ALTER TABLE "PRJ_PROJECT" 
ADD ("VERSION" NUMBER );

ALTER TABLE "PRJ_PROJECT" 
ADD ("VERSION_DATE" DATE );

ALTER TABLE "PRJ_PROJECT" 
ADD ("VERSION_DISPLAY" VARCHAR2(30 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("VERSION_REASON" VARCHAR2(30 BYTE) );

ALTER TABLE "PRJ_PROJECT" 
ADD ("VERSION_NOTE" VARCHAR2(2000 BYTE) );