ALTER TABLE "SYS_USER" 
ADD ("SUPPLIER_ID" NUMBER(20) );

ALTER TABLE "SYS_USER" 
ADD ("OA_KEY" VARCHAR2(4000 ) );

ALTER TABLE "SYS_USER" 
ADD ("LAST_LOGIN_DATE" TIMESTAMP(6) );

ALTER TABLE "SYS_USER" 
ADD ("LAST_PASSWORD_UPDATE_DATE" TIMESTAMP(6) );

ALTER TABLE "SYS_USER" 
ADD ("FIRST_LOGIN" VARCHAR2(1 ) DEFAULT 'Y' );

ALTER TABLE "SYS_USER" 
ADD ("USER_TYPE" VARCHAR2(30 ) );

ALTER TABLE "SYS_USER" 
ADD ("PASSWORD_ENCRYPTED" VARCHAR2(80 ) );

ALTER TABLE "SYS_USER" 
ADD ("EMAIL" VARCHAR2(150 ) );

ALTER TABLE "SYS_USER" 
ADD ("PHONE" VARCHAR2(40 ) );

ALTER TABLE "SYS_USER" 
ADD ("START_ACTIVE_DATE" DATE );

ALTER TABLE "SYS_USER" 
ADD ("END_ACTIVE_DATE" DATE );

ALTER TABLE "SYS_USER" 
ADD ("STATUS" VARCHAR2(30 ) );

ALTER TABLE "SYS_USER" 
ADD ("OBJECT_VERSION_NUMBER" NUMBER(20) DEFAULT '1' );

ALTER TABLE "SYS_USER" 
ADD ("REQUEST_ID" NUMBER(20) DEFAULT '-1' );

ALTER TABLE "SYS_USER" 
ADD ("PROGRAM_ID" NUMBER(20) DEFAULT '-1' );

ALTER TABLE "SYS_USER" 
ADD ("LAST_UPDATE_LOGIN" NUMBER(20) DEFAULT '-1' );

ALTER TABLE "SYS_USER" 
ADD ("ATTRIBUTE_CATEGORY" VARCHAR2(30 ) );

ALTER TABLE "SYS_USER" 
ADD ("ATTRIBUTE1" VARCHAR2(240 ) );

ALTER TABLE "SYS_USER" 
ADD ("ATTRIBUTE2" VARCHAR2(240 ) );

ALTER TABLE "SYS_USER" 
ADD ("ATTRIBUTE3" VARCHAR2(240 ) );

ALTER TABLE "SYS_USER" 
ADD ("ATTRIBUTE4" VARCHAR2(240 ) );

ALTER TABLE "SYS_USER" 
ADD ("ATTRIBUTE5" VARCHAR2(240 ) );

ALTER TABLE "SYS_USER" 
ADD ("ATTRIBUTE6" VARCHAR2(240 ) );

ALTER TABLE "SYS_USER" 
ADD ("ATTRIBUTE7" VARCHAR2(240 ) );

ALTER TABLE "SYS_USER" 
ADD ("ATTRIBUTE8" VARCHAR2(240 ) );

ALTER TABLE "SYS_USER" 
ADD ("ATTRIBUTE9" VARCHAR2(240 ) );

ALTER TABLE "SYS_USER" 
ADD ("ATTRIBUTE10" VARCHAR2(240 ) );

ALTER TABLE "SYS_USER" 
ADD ("ATTRIBUTE11" VARCHAR2(240 ) );

ALTER TABLE "SYS_USER" 
ADD ("ATTRIBUTE12" VARCHAR2(240 ) );

ALTER TABLE "SYS_USER" 
ADD ("ATTRIBUTE13" VARCHAR2(240 ) );

ALTER TABLE "SYS_USER" 
ADD ("ATTRIBUTE14" VARCHAR2(240 ) );

ALTER TABLE "SYS_USER" 
ADD ("ATTRIBUTE15" VARCHAR2(240 ) );


UPDATE SYS_USER s1 SET PASSWORD_ENCRYPTED = ( SELECT ENCRYPTED_USER_PASSWORD FROM SYS_USER s2 WHERE s1.USER_ID = s2.USER_ID );
